export const COLUMNS_CONFIG = [
    {
      key: 'pos',
      short_key: 'pos',
      class: 'si-position',
      showData: true,
      display_name: 'pos',
      type: 'pos',
      display_name_short: 'pos',
    },
    {
      key: 'name',
      short_key: 'short_name',
      image_key: 'id',
      class: 'si-team',
      showData: true,
      display_name: 'team',
      type: 'team',
      display_name_short: 'team',
    },
    {
      key: 'p',
      short_key: 'p',
      class: 'si-play',
      showData: true,
      display_name: 'played',
      type: 'played',
      display_name_short: 'pld',
    },
    {
      key: 'w',
      short_key: 'w',
      class: 'si-won',
      display_name: 'won',
      type: 'won',
      display_name_short: 'w',
    },
    {
      key: 'l',
      short_key: 'l',
      class: 'si-lost',
      display_name: 'lost',
      type: 'lost',
      display_name_short: 'l',
    },
    {
      key: 'nr',
      short_key: 'nr',
      class: 'si-noresult',
      display_name: 'n/r',
      type: 'nr',
      display_name_short: 'n/r',
    },
    {
      key: 't',
      short_key: 't',
      class: 'si-draw',
      display_name: 'tied',
      type: 'tied',
      display_name_short: 't',
    },
    {
      key: 'nrr',
      short_key: 'nrr',
      class: 'si-nrr',
      showData: true,
      display_name: 'net rr',
      type: 'nrr',
      display_name_short: 'nrr',
    },
    {
      key: 'pts',
      short_key: 'pts',
      class: 'si-points',
      showData: true,
      display_name: 'points',
      type: 'points',
      display_name_short: 'pts',
    },
];

export const SERIES_IDS = [5612, 6422];

export const TEAM_IMG = 'https://assets-icc.sportz.io/static-assets/buildv3-stg/images/teams/{{TEAM_ID}}.png?v=1';